---
# tasks file for zabbix-agent_nginx
  - name: Download zabbix-release_5.0-1+bionic_all.deb
    get_url:
      url: https://repo.zabbix.com/zabbix/5.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_5.0-1+bionic_all.deb
      dest: /tmp/zabbix-release_5.0-1+bionic_all.deb

  - name: Install a .deb package
    apt:
      deb: /tmp/zabbix-release_5.0-1+bionic_all.deb
      update_cache: no


  - name: Upgrade the OS (apt-get dist-upgrade)
    apt:
      update_cache: yes
      upgrade: dist


  - name: Install a list of packages
    apt:
      pkg:
      - zabbix-agent
      - nginx
    notify:
      nginx start
  
  - name: Add zabbix-agent config
    template: src=zabbix_agentd.conf dest=/etc/zabbix/zabbix_agentd.conf
    notify:
      zabbix-agent restart 


